### ISSUE TITLE
Notifications of incoming e-mails do not arrive and sometimes, when opening the app, one is forced to log in again

### ISSUE THREAD

**Issue by 7ukunft** [Mailfence/mailfence-android#1]
This happens on my Honor 9 Lite (Android 9, EMUI 9.1.0)

**Comment by Mailfence** [comment]
Dear,

We thank you for this feedback
The notifications are planned for a following release

Regards,

joel

On Oct 13, 2023 at 1:01 PM, 7ukunft ***@***.***> wrote:

This happens on my Honor 9 Lite (Android 9, EMUI 9.1.0)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Mailfence Support

 Secure and private emailp:+32 (0)2 647 92 35a:Chaussée de la Hulpe 181, 1170 Brussels - Belgiumb:blog.mailfence.com Twitter: @pdeschutter
